### ISSUE TITLE
Only one output saves when click download

### ISSUE THREAD

**Issue by wielka-gra** [LambdaLabsML/lambda-diffusers#4]
I have set `num_outputs=2` and when I click download only one (rightmost) saves

**Comment by justinpinkney** [comment]
Could you elaborate what you're referring to re. 'clicking download'?

**Comment by wielka-gra** [comment]
I mean button on site https://replicate.com/lambdal/text-to-pokemon <br>
![Screenshot from 2022-09-28 16-03-19](https://user-images.githubusercontent.com/103772266/192799758-4ac2a238-5856-402e-9466-59c51c137f6d.png)

On the screen You can see all downloaded (by clicking the button) images (1/2)

**Comment by justinpinkney** [comment]
I guess that's an issue with replicate.com rather than the model
